//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace FieldEffect.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("FieldEffect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery #{0}.
        /// </summary>
        internal static string BatteryName {
            get {
                return ResourceManager.GetString("BatteryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon BattLevel {
            get {
                object obj = ResourceManager.GetObject("BattLevel", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Battery Info.  Serialized Response: {0}.
        /// </summary>
        internal static string DebugMsgReceivedBattInfo {
            get {
                return ResourceManager.GetString("DebugMsgReceivedBattInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Battery Info.  Serialized Request: {0}.
        /// </summary>
        internal static string DebugMsgRequestingBattInfo {
            get {
                return ResourceManager.GetString("DebugMsgRequestingBattInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BattMon server-side component exiting..
        /// </summary>
        internal static string InfoMsgBattMonExit {
            get {
                return ResourceManager.GetString("InfoMsgBattMonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BattMon server-side component has started..
        /// </summary>
        internal static string InfoMsgBattMonStart {
            get {
                return ResourceManager.GetString("InfoMsgBattMonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BattMon remote battery monitor is still running in the background.  To exit, right-click on this icon, and choose &quot;Exit&quot;..
        /// </summary>
        internal static string MinimizedMessage {
            get {
                return ResourceManager.GetString("MinimizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BattMon has been minimized.
        /// </summary>
        internal static string MinimizedTitle {
            get {
                return ResourceManager.GetString("MinimizedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon NoBatt {
            get {
                object obj = ResourceManager.GetObject("NoBatt", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No remote batteries found..
        /// </summary>
        internal static string NoBattFound {
            get {
                return ResourceManager.GetString("NoBattFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Battery: {0}%.
        /// </summary>
        internal static string RemoteBatteryText {
            get {
                return ResourceManager.GetString("RemoteBatteryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Batt Level Unknown.
        /// </summary>
        internal static string RemoteBatteryUnknown {
            get {
                return ResourceManager.GetString("RemoteBatteryUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Field-Effect-LLC/RDP-BattMon.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static Icon UnkBatt {
            get {
                object obj = ResourceManager.GetObject("UnkBatt", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
